### ISSUE TITLE
Error (`unknown flag: --output`) while pull python image

### ISSUE THREAD

**Issue by suhailvs** [bRuttaZz/devc#1] opened 2024-02-12 05:59 UTC
while i pull the image it shows error: `unknown flag: --output`.

```
$ devc pull alpine env
unknown flag: --output

[Error] : [pull error] : exit status 125
```

Also when I build the folder with `Dockerfile` it also shows error:  `unknown flag: --output`.
```
devc build devenv
unknown flag: --output
```

**Comment by bRuttaZz** [comment] 2024-02-12 06:22
Think, it should be an issue with buildah dependency. -  Can you please share the result `buildah --version`

**Comment by suhailvs** [comment] 2024-02-12 06:26
`buildah version 1.23.1 (image-spec 1.0.1, runtime-spec 1.0.2-dev)`

**Comment by bRuttaZz** [comment] 2024-02-12 06:39
That's interesting, we are using this `--output` option of buildah that's not available in this version. Can you please update buildah,  `sudo apt-get install buildah` or something (yeah it will basically reinstall with the latest version)  (assuming you are on ubuntu).
Check if the buildah version is near **1.34.0** :)
Let me know the status

**Comment by bRuttaZz** [comment] 2024-02-12 06:41
Should update with a packaging system I think (to resolve such issues)

**Comment by suhailvs** [comment] 2024-02-12 08:25
on Ubuntu 22.04.3 LTS, it says buildah is already the newest version 1.23.
```
$ sudo apt-get install buildah
buildah is already the newest version (1.23.1+ds1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by bRuttaZz** [comment] 2024-02-12 09:25
Okay, that's interesting. Think like, the latest ubuntu repo is not currently supporting higher versions of buildah. I should probably make the application compatible with  older versions :)
Yeah that sounds like a call for an immediate patch :(

**Comment by bRuttaZz** [comment] 2024-02-13 22:13
Hi @suhailvs , can you checkout the latest release (**v1.1.0**) . Now it support the older versions of buildah as well (the ones available @ ubuntu repo )

**Comment by suhailvs** [comment] 2024-02-14 05:02
new error while the running the pull command

```bash
$ devc pull apline myenv
```


```bash
mkdir /run/containers: permission denied
WARN[0000] failed to shutdown storage: "mkdir /run/containers: permission denied" 
mkdir /run/containers: permission denied
WARN[0000] failed to shutdown storage: "mkdir /run/containers: permission denied" 
/usr/bin/cp: missing destination file operand after '/home/suhail/Desktop/temp/myenv/root'
Try '/usr/bin/cp --help' for more information.
/usr/bin/chmod: cannot access '/home/suhail/Desktop/temp/myenv/root': No such file or directory
at least one container ID must be specified
container ID must be specified
ERRO[0000] exit status 125                              
ERRO[0000] exit status 125                              

[Error] : [devc] mount error : exit status 125
```

**Comment by bRuttaZz** [comment] 2024-02-14 14:56
Yup! It was an issue with the way buildah works on ubuntu. There is a permission issue related to the state directory when it's accessed from our user space in buildah. 
Have fixed the issue. Currently we are creating a new state directory under `~/.cache/devc` and it will resolve this issue.

Also the binaries are tested on an ubuntu machine as well. So for the most part it should work, besides, the existing problem of gpg key updates inside debian based container environment when runnung using proot (where I also planning to directly use runc in rootless mode as well, still it's not resolved though)

**The issue is sorted out in ubuntu. Can you please have a check again..**

**Comment by suhailvs** [comment] 2024-02-15 04:20
after reinstalled and pull the repo, still got error:

`$ devc pull apline myenv`

```bash
short-name "apline" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
ERRO[0000] exit status 125                              
ERRO[0000] exit status 125                              

[Error] : [devc] mount error : exit status 125
```

**Comment by bRuttaZz** [comment] 2024-02-15 04:31
Yeah its actually the name, I mean it's `alpine` I think you spelled `apline`. Can you try it again.

**Comment by suhailvs** [comment] 2024-02-15 04:56
`$ devc pull alpine myenv`
```
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob 4abcf2066143 done  
Copying config 05455a0888 done  
Writing manifest to image destination
Storing signatures
a84801fd1155bb5b4992ba8f3eee5cfafa8b8a0b6335ec21af547f46f42c41a7
a84801fd1155bb5b4992ba8f3eee5cfafa8b8a0b6335ec21af547f46f42c41a7
[proot setup] no cache found! attempt downloading.. cache not found (/home/suhail/.cache/devc/proot)
downloading : [/home/suhail/Desktop/temp/myenv/bin/proot] 100%
[devc] env created : myenv

[devc] tada! the env is all yours : [myenv]
```

**Comment by bRuttaZz** [comment] 2024-02-15 05:00
Great That's it :)
You can now start using it.
Let me close this thread.

**Closed by bRuttaZz** 2024-02-15 05:00 UTC
